apiVersion: v1
kind: ServiceAccount
metadata:
  name: rabbitmq-controller-manager
  namespace: knative-sources
secrets:
- name: rabbitmq-source-key
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-source-key
  namespace: knative-sources
type: Opaque
data:
  password: Z3Vlc3Q=
  user: Z3Vlc3Q=
---
apiVersion: v1
kind: Namespace
metadata:
  name: knative-sources