apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    eventing.knative.dev/source: "true"
  name: rabbitmqsources.sources.eventing.knative.dev
spec:
  group: sources.eventing.knative.dev
  names:
    categories:
      - all
      - knative
      - eventing
      - sources
    kind: RabbitmqSource
    plural: rabbitmqsources
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
